version: '3.8'

services:
  academy-ui: 
    image: academy-front:latest
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.academy-front.entrypoints=http"
        - "traefik.http.routers.academy-front.rule=Host(`academy-front.sistemaagil.net`)"
        - "traefik.http.middlewares.academy-front-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.academy-front.middlewares=academy-front-https-redirect"
        - "traefik.http.routers.academy-front-secure.entrypoints=https"
        - "traefik.http.routers.academy-front-secure.rule=Host(`academy-front.sistemaagil.net`)"
        - "traefik.http.routers.academy-front-secure.tls=true"
        - "traefik.http.routers.academy-front-secure.tls.certresolver=http"
        - "traefik.http.routers.academy-front-secure.service=academy-front"
        - "traefik.http.services.academy-front.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true
